### ISSUE TITLE
NameError: name 'G' is not defined

### ISSUE THREAD

**Issue by neo-2020** [AlxndrMlk/Barabasi-Albert_Network#2]
After running code,

def k_distrib(graph=G, scale='lin', colour='#40a6d1', alpha=.8, expct_lo=1, expct_hi=10, expct_const=1): - This line gives error: NameError: name 'G' is not defined

**Comment by AlxndrMlk** [comment]
@neo-2020, 

I fixed the bug. The current version should run smoothly.
